PersonnelDepartment/Models/Worker.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonnelDepartment.Models
{
    public class Worker
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string Education { get; set; }
        public string Position { get; set; }
        public string Status { get; set; }
        public byte[] Avatar { get; set; }
    }
}

PersonnelDepartment/ViewModels/ConfirmViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PersonnelDepartment.ViewModels
{
    public class ConfirmViewModel
    {
        public int WorkerId { get; set; }
        [Required]
        [MinLength(36)]
        [MaxLength(36)]
        public string Password { get; set; }
    }
}

PersonnelDepartment/Controllers/WorkersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonnelDepartment.Data;
using PersonnelDepartment.Models;
using PersonnelDepartment.Services;
using PersonnelDepartment.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace PersonnelDepartment.Controllers
{
    public class WorkersController : Controller
    {
        private readonly PDContext db;
        private readonly IConfiguration _configuration;

        public WorkersController(PDContext context, IConfiguration configuration)
        {
            db = context;
            _configuration = configuration;
        }

        public ActionResult Index() => View(db.Workers.ToList());

        public ActionResult Create() => View();

        [HttpPost]
        public async Task<ActionResult> Create(CreateWorkerViewModel model, string act)
        {
            if (ModelState.IsValid)
            {
                byte[] imageData = null;

                using (var binaryReader = new BinaryReader(model.Avatar.OpenReadStream()))
                {
                    imageData = binaryReader.ReadBytes((int)model.Avatar.Length);
                }

                Worker worker = new Worker()
                {
                    FullName = model.FullName,
                    Education = model.Education,
                    Status = model.Status,
                    Email = model.Email,
                    EmailConfirmed = model.EmailConfirmed,
                    Position = model.Position,
                    Avatar = imageData
                };

                await db.AddAsync(worker);
                await db.SaveChangesAsync();

                if (act == "Confirm")
                {
                    return RedirectToAction(act, new { id = worker.Id });
                }
                return RedirectToAction(act);
            }
            return View(model);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Worker worker = await db.Workers.FindAsync(id);
                if (worker != null)
                {
                    EditWorkerViewModel workerView = new EditWorkerViewModel()
                    {
                        Id = worker.Id,
                        FullName = worker.FullName,
                        Education = worker.Education,
                        Email = worker.Email,
                        EmailConfirmed = worker.EmailConfirmed,
                        Position = worker.Position,
                        Status = worker.Status,
                        Picture = worker.Avatar
                    };
                    return View(workerView);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<ActionResult> Edit(EditWorkerViewModel model, string act)
        {
            if (ModelState.IsValid)
            {
                Worker worker = await db.Workers.FindAsync(model.Id);

                if (model.Avatar != null)
                {
                    byte[] imageData = null;

                    using (var binaryReader = new BinaryReader(model.Avatar.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)model.Avatar.Length);
                    }

                    worker.Avatar = imageData;
                }

                worker.FullName = model.FullName;
                worker.Email = model.Email;
                worker.EmailConfirmed = model.EmailConfirmed;
                worker.Position = model.Position;
                worker.Status = model.Status;
                worker.Education = model.Education;


                await db.SaveChangesAsync();

                if (act == "Confirm")
                {
                    return RedirectToAction(act, new { id = worker.Id });
                }
                return RedirectToAction(act);
            }
            return View(model);
        }

        public async Task<IActionResult> Confirm(int? id)
        {
            if (id != null)
            {
                Worker worker = await db.Workers.FindAsync(id);
                if (worker != null)
                {
                    string guid = Guid.NewGuid().ToString();
                    HttpContext.Session.SetString("Password", guid);

                    EmailService service = new EmailService();
                    await service.SendEmailAsync(
                        email: worker.Email,
                        subject: "Подтвердите ваш аккаунт",
                        message: $"Пароль: {guid}",
                        configuration: _configuration);

                    ConfirmViewModel model = new ConfirmViewModel() { WorkerId = worker.Id };

                    return View(model);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Confirm(ConfirmViewModel model)
        {
            if (ModelState.IsValid)
            {
                string password = HttpContext.Session.GetString("Password");
                Worker worker = await db.Workers.FindAsync(model.WorkerId);

                if (worker != null)
                {
                    if (password == model.Password)
                    {
                        worker.EmailConfirmed = true;
                        await db.SaveChangesAsync();
                    }
                    return View("Confirmed", worker);
                }
                return NotFound();
            }
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PersonnelDepartment/Views/Workers/Confirm.cshtml
@model PersonnelDepartment.ViewModels.ConfirmViewModel

@{
}

<p><h2 class="control-header" style="padding-bottom:12px">Верификация адреса электронной почты</h2></p>
<p>На Ваш адрес отправлен одноразовый пароль.</p>
<p>Введите его в поле и нажмите "Далее".</p>

<form method="post" asp-controller="Workers" asp-action="Confirm">
    <div class="form-row">
        <div class="col-lg-4 col-12 validation">
            <div asp-validation-summary="ModelOnly"></div>
        </div>
    </div>
    <input asp-for="WorkerId" hidden="hidden" />
    <div class="form-row">
        <div class="col-lg-4 col-12">
            <label asp-for="Password" class="login-label"></label><br />
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-6 col-12">
            <a asp-controller="Workers" asp-action="Edit" asp-route-id="@Model.WorkerId" class="btn btn-secondary control-button">Назад</a>
            <button type="submit" class="btn btn-primary control-button">
                Далее
            </button>
        </div>
    </div>
</form>

PersonnelDepartment/Views/Workers/Confirmed.cshtml
@model PersonnelDepartment.Models.Worker

@{
}

@if (Model.EmailConfirmed)
{
    <p style="color:limegreen">Верификация email-адреса успешно завершена!</p>
}
else
{
    <p style="color:red">Ошибка верификации!</p>
}

<a asp-controller="Workers" asp-action="Index" class="btn btn-primary control-button">На главную</a>

PersonnelDepartment/Views/Workers/Create.cshtml
@model PersonnelDepartment.ViewModels.CreateWorkerViewModel

@{
}

<h2 class="control-header" style="padding-bottom:12px">Создать нового рабочего</h2>

<form method="post" asp-controller="Workers" asp-action="Create" enctype="multipart/form-data">
    <div class="form-row">
        <div class="col-lg-4 col-12 validation">
            <div asp-validation-summary="ModelOnly"></div>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-4 col-12">
            <label asp-for="Avatar" class="login-label"></label><br />
            <input asp-for="Avatar" class="form-control-file" />
            <span asp-validation-for="Avatar"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-4 col-12">
            <label asp-for="FullName" class="login-label"></label><br />
            <input asp-for="FullName" class="form-control" />
            <span asp-validation-for="FullName"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-2 col-12">
            <label asp-for="Email" class="login-label"></label><br />
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email"></span>
        </div>
        <div class="col-lg-2 col-12">
            <label asp-for="EmailConfirmed" class="login-label"></label><br />
            <input asp-for="EmailConfirmed" hidden="hidden" />
            @if (Model != null && Model.EmailConfirmed)
            {
                <input placeholder="Подтвержден" disabled="disabled" class="form-control" />
            }
            else
            {
                <input placeholder="Не подтвержден" disabled="disabled" class="form-control" />
            }
            <span asp-validation-for="EmailConfirmed"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-2 col-12">
            <label asp-for="Education" class="login-label"></label><br />
            <input asp-for="Education" class="form-control" />
            <span asp-validation-for="Education"></span>
        </div>
        <div class="col-lg-2 col-12">
            <label asp-for="Position" class="login-label"></label><br />
            <input asp-for="Position" class="form-control" />
            <span asp-validation-for="Position"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-4 col-12">
            <label asp-for="Status" class="login-label"></label><br />
            <select asp-for="Status" class="form-control">
                <option>Контракт</option>
                <option>Постоянно</option>
                <option>Временно</option>
                <option>Уволен(а)</option>
            </select>
            <span asp-validation-for="Education"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-6 col-12">
            <button asp-route-act="Index" type="submit" class="btn btn-primary control-button">Сохранить</button>
            <a asp-controller="Workers" asp-action="Index" class="btn btn-secondary control-button">Назад</a>
            <button type="submit" asp-route-act="Confirm" class="btn btn-secondary control-button">
                Подтвердить E-mail
            </button>
        </div>
    </div>
</form>

PersonnelDepartment/Views/Workers/Edit.cshtml
@model PersonnelDepartment.ViewModels.EditWorkerViewModel

@{
}

<h2 class="control-header" style="padding-bottom:12px">Свойства рабочего @Model.FullName</h2>

@if (Model.Picture != null)
{
    <img style='width:80px; height:80px;' src="data:image/png;base64,@(Convert.ToBase64String(Model.Picture))" />
}

<form method="post" asp-controller="Workers" asp-action="Edit" enctype="multipart/form-data">
    <div class="form-row">
        <div class="col-lg-4 col-12 validation">
            <div asp-validation-summary="ModelOnly"></div>
        </div>
    </div>
    <input asp-for="Id" hidden="hidden" />
    <div class="form-row">
        <div class="col-lg-4 col-12">
            <label asp-for="Avatar" class="login-label"></label><br />
            <input asp-for="Avatar" class="form-control-file" />
            <span asp-validation-for="Avatar"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-4 col-12">
            <label asp-for="FullName" class="login-label"></label><br />
            <input asp-for="FullName" class="form-control" />
            <span asp-validation-for="FullName"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-2 col-12">
            <label asp-for="Email" class="login-label"></label><br />
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email"></span>
        </div>
        <div class="col-lg-2 col-12">
            <label asp-for="EmailConfirmed" class="login-label"></label><br />
            <input asp-for="EmailConfirmed" hidden="hidden" />
            @if (Model.EmailConfirmed)
            {
                <input placeholder="Подтвержден" disabled="disabled" class="form-control" />
            }
            else
            {
                <input placeholder="Не подтвержден" disabled="disabled" class="form-control" />
            }
            <span asp-validation-for="EmailConfirmed"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-2 col-12">
            <label asp-for="Education" class="login-label"></label><br />
            <input asp-for="Education" class="form-control" />
            <span asp-validation-for="Education"></span>
        </div>
        <div class="col-lg-2 col-12">
            <label asp-for="Position" class="login-label"></label><br />
            <input asp-for="Position" class="form-control" />
            <span asp-validation-for="Position"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-4 col-12">
            <label asp-for="Status" class="login-label"></label><br />
            <select asp-for="Status" class="form-control">
                <option>Контракт</option>
                <option>Постоянно</option>
                <option>Временно</option>
                <option>Уволен(а)</option>
            </select>
            <span asp-validation-for="Education"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="col-lg-6 col-12">
            <button asp-route-act="Index" type="submit" class="btn btn-primary control-button">Сохранить</button>
            <a asp-controller="Workers" asp-action="Index" class="btn btn-secondary control-button">Назад</a>
            @if (!Model.EmailConfirmed)
            {
                <button type="submit" asp-route-act="Confirm" class="btn btn-secondary control-button">
                    Подтвердить E-mail
                </button>
            }
        </div>
    </div>
</form>

PersonnelDepartment/Views/Workers/Index.cshtml
@model IEnumerable<Worker>

@{
}

<h2 class="special-header" style="padding-bottom:12px">Штат работников предприятия</h2>

<div class="table-responsive">
    <table class="table">
        <tr>
            <th>№</th>
            <th>Фамилия, инициалы</th>
            <th>Фото</th>
            <th>Образование</th>
            <th>Должность</th>
            <th>Статус</th>
            <th>Свойства</th>
        </tr>
        @foreach (var worker in Model)
        {
            <tr>
                <td>@worker.Id</td>
                <td>@worker.FullName</td>
                <th><img style='width:80px; height:80px;' src="data:image/png;base64,@(Convert.ToBase64String(worker.Avatar))" /></th>
                <td>@worker.Education</td>
                <td>@worker.Position</td>
                <td>@worker.Status</td>
                <td>
                    <a class="btn btn-secondary" asp-controller="Workers" asp-action="Edit" asp-route-id="@worker.Id">Свойства</a>
                </td>
            </tr>
        }
    </table>
</div>

<a class="btn btn-primary" asp-controller="Workers" asp-action="Create">Новый</a>